# render.yaml
services:
  - type: web
    name: djorssi-express-api
    runtime: node
    repo: https://github.com/ALEXANDREGBAMELE/djorssi-express-backend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: djorssi-express-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: djorssi-express-redis
          type: keyvalue
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    buildCommand: npm install
    # ✅ Commande pré-déploiement pour créer les tables
    preDeployCommand: npm run migrate
    startCommand: npm start

  - type: keyvalue
    name: djorssi-express-redis
    plan: free

  - type: postgresql
    name: djorssi-express-db
    plan: free
    database: djorssi_express_db
    user: djorssi_user
